(defun altmerge(l1 l2)
    (cond ((null l1) l2) 
        ((null l2) l1)
        (t (cons (car l1) (altmerge l2 (cdr l1)) ))
    )
)
(setf A (altmerge '(1 2 3) '(X Y Z)))
(setf B (altmerge '(W E A W Q) '(1 7 7 3 2 6)))
(setf C (altmerge '(S D (Q W) Q) '(A (3 2))))
(setf D (altmerge nil '(A B C D E)))
(print A)
(print B)
(print C)
(print D)