(defun countup(e l)
	(cond ((null l) 0)
		((equal e (car l)) (+ 1 (countup e (cdr l))))
		(t (countup e (cdr l)))
	)
)
(setf A (countup 'A '(A B C D E)))
(setf B (countup '1 '(1 2 3 2 1)))
(print A)
(print B)