(defun supercrypto(w1 w2)
        (cond ((/= (length w1) (length w2)) nil)
            (t (cryptogram w1 w2))
        )
)
(defun cryptogram(w1 w2)
    (cond ((null w1) (null w2))
        ((equal (where (car w1) (cdr w1)) (where (car w2) (cdr w2))) (cryptogram (cdr w1) (cdr w2)))
        (t nil)
    )
)
(defun where(e l)
    (cond ((null l) 0)
        ((equal e (car l)) 0)
        (t (+ 1 (where e (cdr l))))
    )
)
(setf A (supercrypto '(H E I G H T) '(E I G H T)))
(setf B (supercrypto '(A A A A) '(A A A))) 
(setf C (supercrypto '(A S S E S S) '(V O O D O))) 
(setf D (supercrypto '(A S S E S) '(V O O D O O))) 
(setf E (supercrypto '(A S S E S S) '(V O O D O O)))
(setf F (supercrypto '(C B A C C A B B A) '(A C B A A B C C B)))
(setf G (supercrypto '(T H E S I S) '(H E I S T S)))
(setf H (supercrypto '(P A J A M A) '(S E R E N E)))
(print A)
(print B)
(print C)
(print D)
(print E)
(print F)
(print G)
(print H)