(defun deleteneg(l)
	(cond ((null l) nil)
		((< (car l) 0) (deleteneg (cdr l)))
		(t (cons (car l) (deleteneg (cdr l))))
	)
)
(setf A (deleteneg '(-1 -2 -3 -4 -5)))
(setf B (deleteneg '(-3 -2 -1 0 1 2 3)))
(print A)
(print B)