(defun fib(f s n)
    (cond ((= n 0) nil)
        (t (cons f (fib s (+ f s) (- n 1))))    
    )
)
(setf A (fib 1 1 5))
(print A)
(setf A (fib 3 5 10))
(print A)
(setf A (fib 2 5 10))
(print A)
(setf A (fib 8 11 4))
(print A)
(setf A (fib 0 1 20))
(print A)