(defun pairup(l)
    (cond ((null l) nil)
		((null (cdr l)) (list l))
        (t (append (list (list (car l) (car (cdr l))))(pairup (cdr (cdr l)))))
    )
)
#|| An Alternate Notation for the SAME Function Using Shorthand Notations is:
	(defun pairup(l)
		(cond ((null l) nil)
			((null (cdr l)) (list l))
			(t (append (list (list (car l) (cadr l))) (pairup (cddr l))))
		)
	)
||#
(setf A (pairup '(1 2 3 4 5 6)))
(setf B (pairup '(A B C D E)))
(setf C (pairup '((A) B C (D E))))
(setf D (pairup nil))
(print A)
(print B)
(print C)
(print D)