(defun parens(l)
    (cond ((null (cdr l)) l)
        (t (list (car l) (parens (cdr l))))
    )
)
(setf A (parens '(A B C D E)))
(setf B (parens '(A A A)))
(setf C (parens '(X)))
(setf D (parens '(1 2 (3 4) 5)))
(setf E (parens nil))
(print A)
(print B)
(print C)
(print D)
(print E)