(defun twototen(l)
    (cond ((null l) 0)
        (t (+ (* 2 (twototen (butlast l))) (car (last l))))
    )
)
(setf A (twototen '(1 1 0 1 0 0)))
(setf B (twototen '(1 1 0 1 0 0 0)))
(print A)
(print B)